MusicStore/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
	url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^admin/', admin.site.urls),
    url(r'^mainapp/', include('mainapp.urls')),
]

mainapp/urls.py
from django.conf.urls import url

from . import views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import views as auth_views
 
app_name = 'mainapp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^store/$', views.store, name='store'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^addToCart/$', views.addToCart, name='addToCart'),
    url(r'^deleteFromCart/$', views.deleteFromCart, name='deleteFromCart'),
    url(r'^product/$', views.product, name='product'),
    url(r'^manager/$', views.manager, name='manager'),
    url(r'^deleteProduct/$', views.deleteProduct, name='deleteProduct'),
    url(r'^addProduct/$', views.addProduct, name='addProduct'),
    url(r'^updateProduct/(?P<item_id>[0-9]+)$', views.updateProduct, name='updateProduct'),
    url(r'^confirm/$', views.confirm, name='confirm'),
]

mainapp/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
       
class Type_of_Product(models.Model):
	name=models.CharField(max_length=50)
	
	def __str__(self):
		return self.name
        	
class Users(models.Model):
	user=models.OneToOneField(User, on_delete=models.CASCADE)
	manager=models.BooleanField(default=False)
	
	def __str__(self):
		return self.user.username
	
@receiver(post_save, sender=User)
def create_user_users(sender, instance, created, **kwargs):
    if created:
        Users.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_users(sender, instance, **kwargs):
    instance.users.save()

		
class Product(models.Model):
	name=models.CharField(max_length=50)
	price=models.DecimalField(max_digits=6, decimal_places=2)
	manager_id=models.ForeignKey(Users, on_delete=models.CASCADE)
	category=models.ForeignKey(Type_of_Product, on_delete=models.PROTECT)	
	def __str__(self):
		return self.name
        
class Cart(models.Model):
	quantity=models.IntegerField()
	boughtPrice=models.DecimalField(max_digits=6, decimal_places=2)
	status=models.BooleanField(default=False)
	product_id=models.ForeignKey(Product,on_delete=models.CASCADE)
	users_id=models.ForeignKey(Users,on_delete=models.CASCADE)

	def __str__(self):
		return str(self.product_id)	

class Inventory(models.Model):
	product_id=models.ForeignKey(Product,on_delete=models.CASCADE)
	quantity=models.IntegerField()

	def __str__(self):
		return str(self.product_id)	

mainapp/forms.py
from django import forms
from models import Users,Type_of_Product
from django.contrib.auth.models import User
import re
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator
         
class RegistrationForm(forms.Form):
 
    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, max_length=30,placeholder='Username')), label=_("Username"), error_messages={ 'invalid': _("This value must contain only letters, numbers and underscores.") })
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True, max_length=30,placeholder='Email address')), label=_("Email address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False,placeholder='Choose a password')),min_length=6, label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False,placeholder='Confirm password')), label=_("Password (again)"))
    manager = forms.BooleanField(widget=forms.CheckboxInput(attrs=dict(required=False)),required=False,label=_("Manager"))
    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. Please try another one."))
 
    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data
        
class AddProductForm(forms.Form):
	choices=Type_of_Product.objects.all().values_list()
	numeric = RegexValidator(r'\d+', 'Only numeric characters are allowed.')
	name=forms.CharField(widget=forms.TextInput(attrs=dict(required=True,placeholder='Product Name')))
	price=forms.RegexField(regex=r'^\d+(.\d{1,2})?$', widget=forms.TextInput(attrs=dict(required=True,placeholder='Price')), error_messages = {'invalid': _("Not a valid web address1.")})
	category=forms.ChoiceField(choices=choices, widget=forms.Select(attrs=dict(required=True,placeholder='Type of Product')))
	quantity=forms.CharField(widget=forms.TextInput(attrs=dict(required=True,placeholder='Quantity')),validators=[numeric])
    

mainapp/views.py
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from models import Product,Inventory,Cart,Users,User,Type_of_Product
from mainapp.forms import RegistrationForm,AddProductForm
from django.contrib import messages
from django.template import RequestContext
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render_to_response

def index(request):
	if request.user.is_authenticated():
		user=Users.objects.get(id=request.user.id)
		manager=user.manager
	else:
		manager=False
	return render(request,'index.html',{ 'manager' : manager})
    
@login_required()
def store(request):
	user=Users.objects.get(id=request.user.id)
	manager=user.manager
	items=Inventory.objects.all()
	return render(request,'store.html',{ 'items' : items,'manager' : manager })
    
@login_required()
def cart(request):
	user=Users.objects.get(id=request.user.id)
	manager=user.manager
	cart=Cart.objects.filter(users_id__user=request.user).order_by('status')
	return render(request,'cart.html',{ 'cart' : cart,'manager' : manager })

@csrf_protect
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1'],
            email=form.cleaned_data['email']
            )
            users=Users.objects.get(user=user)
            users.manager=form.cleaned_data['manager']
            users.save()
            return HttpResponseRedirect('/mainapp/')
    else:
		user=Users.objects.get(id=request.user.id)
		manager=user.manager
		form = RegistrationForm()
    variables = RequestContext(request, {
    'form': form,
    'manager' : manager
    })
 
    return render_to_response(
    'register.html',
    variables,
    )
        
def login(request):
    return render(request,'login.html')

def logout(request):
    return render(request,'logout.html')
    
@login_required()
def addToCart(request):
	item = get_object_or_404(Inventory, pk=request.POST['item_id'])
	user=Users.objects.get(id=request.user.id)
	cart=Cart(quantity=1, boughtPrice=item.product_id.price,product_id=item.product_id,users_id=user)
	cart.save()
	item.quantity=item.quantity-1
	item.save()
	return HttpResponse(user)

@login_required()
def deleteFromCart(request):
	item = get_object_or_404(Cart, pk=request.POST['item_id'])
	if not item.status:
		item.delete()
	return HttpResponse(True)

@login_required()
def manager(request):
	return render(request,'manager.html')

@login_required()		
def product(request):
	products=Inventory.objects.filter(product_id__manager_id=request.user.id)	
	return render(request,'product.html',{'items':products})

@csrf_protect	
def addProduct(request):
	if request.method == 'POST':
		form = AddProductForm(request.POST)
		if form.is_valid():
			cat=Type_of_Product.objects.get(id=form.cleaned_data['category'])
			product = Product.objects.create(
			name=form.cleaned_data['name'],
			price=form.cleaned_data['price'],
			category=cat,
			manager_id=Users.objects.get(user=request.user)
			)
			inventory=Inventory.objects.create(product_id=product,quantity=form.cleaned_data['quantity'])
			return HttpResponseRedirect('/mainapp/product')
	else:
		form = AddProductForm()
		variables = RequestContext(request, {'form': form})
		return render_to_response('add.html',variables)

@csrf_protect
def deleteProduct(request):
	i=get_object_or_404(Inventory, pk=request.POST['item_id'])
	item = get_object_or_404(Product, pk=i.product_id.id)
	item.delete()
	return render_to_response('product.html')	

def updateProduct(request,item_id):
	if request.method == 'POST':
		form = AddProductForm(request.POST)
		if form.is_valid():
			cat=Type_of_Product.objects.get(id=form.cleaned_data['category'])
			i=get_object_or_404(Inventory, pk=item_id)
			p=get_object_or_404(Product, pk=i.product_id.id)
			p.name=form.cleaned_data['name']
			p.price=form.cleaned_data['price']
			p.category=cat
			p.save()
			i.quantity=form.cleaned_data['quantity']
			i.save()
			return HttpResponseRedirect('/mainapp/product')
	else:
		item=get_object_or_404(Inventory, pk=item_id)
		form = AddProductForm(initial={'name': item.product_id.name,'price':item.product_id.price,'quantity':item.quantity,'category':item.product_id.category.id})
		variables = RequestContext(request, {'form': form})
		return render_to_response('updateProduct.html',variables)	
	
def confirm(request):
	if request.method == 'POST':
		item=item = get_object_or_404(Cart, pk=request.POST['item_id'])
		item.status=True
		item.save()
		return HttpResponse(True)
	else:
		cart=Cart.objects.filter(product_id__manager_id__user=request.user)
		return render(request,'confirm.html',{'items':cart})
		

mainapp/templates/add.html
{% load static %}
{% load widget_tweaks %}

  <head>
    <title>Manager | Add Product</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "styles/style.css" %}">
    <link rel="stylesheet" href="{% static "styles/register.css" %}">
    <script src="{% static "scripts/jquery-3.1.1.min.js " %}"></script>
    <script src="{% static "scripts/script.js" %}"></script>

  </head>

  <body>




   <div id="menu">
      <ul class="ic_menu site_genisligi">
        <li>
          <a href="{% url 'mainapp:index' %}">Home</a>
        </li> 

        <li>
          <a href="{% url 'mainapp:product' %}">Product</a>
        </li>
		<li>
          <a href="{% url 'mainapp:confirm' %}">Confirm</a>
        </li>
        <li>
          <a href="{% url 'mainapp:logout' %}">Logout</a>
        </li> 
      </ul>
    </div>




<div class="site_genisligi sayfa_yapisi">
    <!--Main Body-->
<div class="container" >	
    <div class="col-md-6" >
        <div id="logbox"  >
            <form id="signup" method="post" >
                <h1>Add a Product</h1>
                {% csrf_token %}
                <div id="alert_message" class="{%if form.errors%}alert alert-danger{%else%}ghost{%endif%}">
         			{{form.non_field_errors}} 
         			{{form.name.errors}}
         			{{form.price.errors}}
         			{{form.quantity.errors}} 
         			{{form.product.errors}}            
    			</div>
                {{form.name|add_class:'input' }}
                {{form.price|add_class:'input'}}
                {{form.quantity|add_class:'input'}}
                <label style="padding-left:40%;" for="{{ form.category_for_label }}">Category :</label>
           		{{form.category|add_class:'input'}}
                
				 <input type="submit" value="Add!" class="inputButton"/>

            </form>
        </div>
    </div>
    <!--col-md-6-->


</div>

</div>

</body>

</html>
<script>
window.setTimeout(function() {
  $("#alert_message").fadeTo(500, 0).slideUp(500, function(){
    $(this).remove(); 
  });
}, 3000);
</script>

mainapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
    <title>Online Music Store</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "styles/style.css" %}">
    <link rel="stylesheet" href="{% static "styles/register.css" %}">
    <script src="{% static "scripts/jquery-3.1.1.min.js " %}"></script>
    <script src="{% static "scripts/script.js" %}"></script>

  </head>

  <body>
    <div id="menu">
      <ul class="ic_menu site_genisligi">
        <li>
          <a href="{% url 'mainapp:index' %}">Home</a>
        </li> 

        <li>
          <a href="{% url 'mainapp:store' %}">Store</a>
        </li> 

        <li>
          <a href="{% url 'mainapp:cart'%}">Cart</a>
        </li> 
        {%if manager%}
 		<li>
          <a href="{% url 'mainapp:manager' %}">Manager</a>
        </li> 
        {%endif%}
        <li>
          <a href="{% url 'mainapp:register' %}">Register</a>
        </li> 

        <li>
          <a href="{% url 'mainapp:login' %}">Login</a>
        </li> 

        <li>
          <a href="{% url 'mainapp:logout' %}">Logout</a>
        </li> 
      </ul>
    </div>

	<div class="site_genisligi sayfa_yapisi">
		
		{% block content %}
    	{% endblock %}

	</div>

  </body>

</html>
{% block script %}
{% endblock %}

mainapp/templates/cart.html
{% extends 'base.html' %}

{% block content %}
    
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Cart</div>
  <div class="panel-body">
    <p>Products that you choosed: </p>
  </div>

  <!-- Table -->
  <table class="table table-hover table-striped">
  	{% if cart %} 	
	<tr>
		<th>Product Name</th>
		<th>Price</th> 
		<th>Stock</th>
		<th>Status</th>
		<th width="10%"></th>
	</tr>
	{% for item in cart %}
	<tr>
		<td>{{item.product_id.name }}</td>
		<td>{{item.boughtPrice}}</td>
		<td>{{item.quantity}}</td>
		<td>{{item.status}}</td>		
		<td>
		{%if not item.status%}
		<a href="" id = "{{ item.id }}" onClick="sendData(this.id)"><span class="glyphicon glyphicon-minus" aria-hidden="true" ></span></a></td>
		{%endif%}
	</tr>
	{% endfor %}
    {% else %}
    <div class="well well-lg"><p>No products are available.</p></div>
    {% endif %}
  </table>
</div>
{% endblock %}
{% block script %}
<script>
    function sendData(item_id){
    $.ajax({
                 type:"POST",
                 url:"{%url 'mainapp:deleteFromCart' %}",
                 data: { item_id: item_id,
                 		csrfmiddlewaretoken: '{{ csrf_token }}'
                  },
                 
            });
		return false;
    }

</script>
{% endblock %}

mainapp/templates/confirm.html
<html>
{% load static %}


  <head>
    <title>Manager | Confirm</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static "styles/style.css" %}">
    <script src="{% static "scripts/jquery-3.1.1.min.js " %}"></script>
    <script src="{% static "scripts/script.js" %}"></script>

  </head>

  <body>




	<div id="menu">
		<ul class="ic_menu site_genisligi">
		<li>
			<a href="{% url 'mainapp:index' %}">Home</a>
		</li> 
		<li>
			<a href="{% url 'mainapp:product' %}">Product</a>
		</li>
		<li>
			<a href="{% url 'mainapp:confirm' %}">Confirm</a>
		</li>
		<li>
			<a href="{% url 'mainapp:logout' %}">Logout</a>
		</li> 
		</ul>
	</div>




<div class="site_genisligi sayfa_yapisi">
    
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Confirm Page</div>
  <div class="panel-body">
    <p>Products that you added: </p>
  </div>

  <!-- Table -->
  <table class="table table-hover table-striped">
  	{% if items %} 	
	<tr>
		<th>Product Name</th>
		<th>Price</th> 
		<th>Quantity</th>
		<th width="10%"></th>
	</tr>
	{% for item in items %}
	{% if not item.status %} 
	<tr>
		<td>{{item.product_id.name }}</td>
		<td>{{item.boughtPrice}}</td>
		<td>{{item.quantity}}</td>		
		<td><a href="" id = "{{ item.id }}" onClick="sendData(this.id)"><span class="glyphicon glyphicon-ok" aria-hidden="true" ></span></a></td>
	</tr>
	{% endif %}
	{% endfor %}
    {% else %}
    <div class="well well-lg"><p>No products are available.</p></div>
    {% endif %}
  </table>
</div>

</div>

</body>

</html>

<script>
    function sendData(item_id){
    $.ajax({
                 type:"POST",
                 url:"{%url 'mainapp:confirm' %}",
                 data: { item_id: item_id,
                 		csrfmiddlewaretoken: '{{ csrf_token }}'
                  },
                 
            });
		return false;
    }

</script>

mainapp/templates/index.html
{% extends 'base.html' %}


{% block content %}
 <div class="panel panel-default" style="height:25%;">
  <div class="panel-heading">
    <h1 class="panel-title" ><b>. : Welcome : .</b></h1>
  </div>
  <div class="panel-body" style="font-size:62px;">
    This is Online Music Store !
  </div>
</div>
{% endblock %}

mainapp/templates/manager.html
<html>
{% load static %}


  <head>
    <title>Post IT</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "styles/style.css" %}">
    <script src="{% static "scripts/jquery-3.1.1.min.js " %}"></script>
    <script src="{% static "scripts/script.js" %}"></script>

  </head>

  <body>




    <div id="menu">
      <ul class="ic_menu site_genisligi">
        <li>
          <a href="{% url 'mainapp:index' %}">Home</a>
        </li> 

        <li>
          <a href="{% url 'mainapp:product' %}">Product</a>
        </li>
        <li>
          <a href="{% url 'mainapp:confirm' %}">Confirm</a>
        </li> 

        <li>
          <a href="{% url 'mainapp:logout' %}">Logout</a>
        </li> 
      </ul>
    </div>




<div class="site_genisligi sayfa_yapisi">
    
<div class="panel panel-default" style="height:25%;">
  <div class="panel-heading">
    <h1 class="panel-title" ><b>. : Welcome : .</b></h1>
  </div>
  <div class="panel-body" style="font-size:62px;">
    This is Manager page !
  </div>
</div>

</div>

</body>

</html>

mainapp/templates/product.html

<html>
{% load static %}


  <head>
    <title>Online Music Store | Manager</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "styles/style.css" %}">
    <script src="{% static "scripts/jquery-3.1.1.min.js " %}"></script>
    <script src="{% static "scripts/script.js" %}"></script>

  </head>

  <body>




    <div id="menu">
      <ul class="ic_menu site_genisligi">
        <li>
          <a href="{% url 'mainapp:index' %}">Home</a>
        </li> 

        <li>
          <a href="{% url 'mainapp:product' %}">Product</a>
        </li> 
        <li>
          <a href="{% url 'mainapp:confirm' %}">Confirm</a>
        </li>
		
        <li>
          <a href="{% url 'mainapp:logout' %}">Logout</a>
        </li> 
      </ul>
    </div>




<div class="site_genisligi sayfa_yapisi">
    
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title" ><b>. : This is Add Music panel ! : .</b></h1>
  </div>
  <div class="panel-body">
    <p>All Products You Have! </p>
    <a href="{%url 'mainapp:addProduct' %}" class="btn btn-sm btn-success" style="float:right;"><span class="glyphicon glyphicon-plus"></span> Add</a>
  </div>

<!-- Table -->
  <table class="table table-hover table-striped">
  	{% if items %} 	
	<tr>
		<th>Product Name</th>
		<th>Price</th> 
		<th>Stock</th>
		<th width="10%"></th>
	</tr>
	{% for item in items %}
	<tr>
		<td>{{item.product_id.name}}</td>
		<td>{{item.product_id.price}}</td>
		<td>{{item.quantity}}</td>		
		<td><a href="{% url 'mainapp:updateProduct' item.id %}" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-pencil"></span></a><a id = "{{ item.id }}" onClick="sendDataToDelete(this.id)" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-trash"></span></a></td>
	</tr>
	{% endfor %}
    {% else %}
    <div class="well well-lg"><p>No products are available.</p></div>
    {% endif %}
  </table>
</div>
</div>

</body>

</html>
<script>
    function sendDataToDelete(item_id){
    $.ajax({
                 type:"POST",
                 url:"{%url 'mainapp:deleteProduct' %}",
                 data: { item_id: item_id,
                 		csrfmiddlewaretoken: '{{ csrf_token }}'
                  },
                 
            });
            location.reload();
		return false;
    }

</script>

mainapp/templates/store.html
{% extends 'base.html' %}

{% block content %}
	<div class="panel panel-default">
	  <!-- Default panel contents -->
	  <div class="panel-heading">Music Store</div>
	  <div class="panel-body">
		<p>You can choose a music that you want to buy ! </p>
	  </div>

	  <!-- Table -->
	  <table class="table table-hover table-striped">
	  	{% if items %} 	
		<tr>
			<th>Product Name</th>
			<th>Price</th> 
			<th>Stock</th>
			<th width="10%"></th>
		</tr>
		{% for item in items %}
		<tr>
			<td>{{item.product_id.name }}</td>
			<td>{{item.product_id.price}}</td>
			<td>{{item.quantity}}</td>
			<td><a href="" id = "{{ item.id }}" onClick="sendData(this.id)"><span class="glyphicon glyphicon-plus" aria-hidden="true" ></span></a></td>
		</tr>
		{% endfor %}
		{% else %}
		<div class="well well-lg"><p>No products are available.</p></div>
		{% endif %}
	  </table>
	</div>

{% endblock %}
{% block script%}
<script>
    function sendData(item_id){
    $.ajax({
                 type:"POST",
                 url:"{%url 'mainapp:addToCart' %}",
                 data: { item_id: item_id,
                 		csrfmiddlewaretoken: '{{ csrf_token }}'
                  },
                 
            });
		return false;
    }

</script>
{% endblock %}

mainapp/templates/updateProduct.html
{% load static %}
{% load widget_tweaks %}

  <head>
    <title>Manager | Update Product</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "styles/style.css" %}">
    <link rel="stylesheet" href="{% static "styles/register.css" %}">
    <script src="{% static "scripts/jquery-3.1.1.min.js " %}"></script>
    <script src="{% static "scripts/script.js" %}"></script>

  </head>

  <body>




   <div id="menu">
      <ul class="ic_menu site_genisligi">
        <li>
          <a href="{% url 'mainapp:index' %}">Home</a>
        </li> 

        <li>
          <a href="{% url 'mainapp:product' %}">Product</a>
        </li>
		<li>
          <a href="{% url 'mainapp:confirm' %}">Confirm</a>
        </li>
        <li>
          <a href="{% url 'mainapp:logout' %}">Logout</a>
        </li> 
      </ul>
    </div>




<div class="site_genisligi sayfa_yapisi">
    <!--Main Body-->
<div class="container" >	
    <div class="col-md-6" >
        <div id="logbox"  >
            <form id="signup" method="post" >
                <h1>Update Product</h1>
                {% csrf_token %}
                <div id="alert_message" class="{%if form.errors%}alert alert-danger{%else%}ghost{%endif%}">
         			{{form.non_field_errors}} 
         			{{form.name.errors}}
         			{{form.price.errors}}
         			{{form.quantity.errors}} 
         			{{form.product.errors}}            
    			</div>
                {{form.name|add_class:'input' }}
                {{form.price|add_class:'input'}}
                {{form.quantity|add_class:'input'}}
                <label style="padding-left:40%;" for="{{ form.category_for_label }}">Category :</label>
           		{{form.category|add_class:'input'}}
                
				 <input type="submit" value="Update!" class="inputButton"/>

            </form>
        </div>
    </div>
    <!--col-md-6-->


</div>

</div>

</body>

</html>
<script>
window.setTimeout(function() {
  $("#alert_message").fadeTo(500, 0).slideUp(500, function(){
    $(this).remove(); 
  });
}, 3000);
</script>